--------------------------------------------------------
--  File created - wtorek-grudnia-08-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for DB Link PLUG_CARS_DB
--------------------------------------------------------

  CREATE DATABASE LINK "PLUG_CARS_DB"
   USING 'plug_cars_db';
--------------------------------------------------------
--  DDL for Table RENTERS
--------------------------------------------------------

  CREATE TABLE "CAR_RENTAL"."RENTERS" 
   (	"ID" NUMBER(19,2), 
	"EMAIL" VARCHAR2(320 CHAR), 
	"NAME" VARCHAR2(40 CHAR), 
	"PHONE" VARCHAR2(9 CHAR), 
	"SURNAME" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "CAR_RENTAL"."BOOKING" 
   (	"ID" NUMBER(19,2), 
	"PRICE" FLOAT(126), 
	"SINCE" DATE, 
	"UNTIL" DATE, 
	"CAR" NUMBER(19,2), 
	"RENTER" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010569
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAR_RENTAL"."SYS_C0010569" ON "CAR_RENTAL"."BOOKING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010006
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAR_RENTAL"."SYS_C0010006" ON "CAR_RENTAL"."RENTERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RENTERS
--------------------------------------------------------

  ALTER TABLE "CAR_RENTAL"."RENTERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CAR_RENTAL"."RENTERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."RENTERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "CAR_RENTAL"."BOOKING" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("RENTER" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("CAR" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("UNTIL" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("SINCE" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger BOOKING_SORT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CAR_RENTAL"."BOOKING_SORT_TRG" 
AFTER INSERT ON BOOKING
FOR EACH ROW
DECLARE
  TYPE renter_row IS RECORD (
    ID renters.id%TYPE,
    EMAIL renters.email%TYPE,
    NAME renters.name%TYPE,
    PHONE renters.phone%TYPE,
    SURNAME renters.surname%TYPE
  );
  renter renter_row;
BEGIN
  DELETE FROM BOOKING_WRO WHERE ID = :NEW.ID;
  SELECT * INTO renter FROM RENTERS_WRO WHERE ID = :NEW.RENTER;
  INSERT INTO RENTERS (ID, EMAIL, NAME, PHONE, SURNAME) VALUES (renter.ID, renter.EMAIL, renter.NAME, renter.PHONE, renter.SURNAME);
  DELETE FROM RENTERS_WRO WHERE ID = :NEW.RENTER;
END;
/
ALTER TRIGGER "CAR_RENTAL"."BOOKING_SORT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn RENTERS_WRO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "CAR_RENTAL"."RENTERS_WRO" FOR "CAR_RENTAL"."RENTERS"@"PLUG_CARS_DB";
--------------------------------------------------------
--  DDL for Synonymn BOOKING_WRO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "CAR_RENTAL"."BOOKING_WRO" FOR "CAR_RENTAL"."BOOKING"@"PLUG_CARS_DB";
