--------------------------------------------------------
--  File created - niedziela-grudnia-13-2015   
--------------------------------------------------------
DROP TABLE "CAR_RENTAL"."BOOKING" cascade constraints;
DROP TABLE "CAR_RENTAL"."CARS" cascade constraints;
DROP TABLE "CAR_RENTAL"."RENTERS" cascade constraints;
DROP SYNONYM "CAR_RENTAL"."BOOKING_WRO";
DROP SYNONYM "CAR_RENTAL"."CARS_WRO";
DROP SYNONYM "CAR_RENTAL"."RENTERS_WRO";
DROP DATABASE LINK "CAR_RENTAL"."PLUG_CARS_DB";
--------------------------------------------------------
--  DDL for DB Link PLUG_CARS_DB
--------------------------------------------------------

  CREATE DATABASE LINK "PLUG_CARS_DB"
   USING 'plug_cars_db';
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "CAR_RENTAL"."BOOKING" 
   (	"ID" NUMBER(19,2), 
	"PRICE" FLOAT(126), 
	"SINCE" DATE, 
	"UNTIL" DATE, 
	"CAR" NUMBER(19,2), 
	"RENTER" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARS
--------------------------------------------------------

  CREATE TABLE "CAR_RENTAL"."CARS" 
   (	"ID" NUMBER(19,2), 
	"POWER" NUMBER(5,0), 
	"WEIGHT" NUMBER(5,0), 
	"BODY" NUMBER(19,2), 
	"COLOR" NUMBER(19,2), 
	"WHEELS" NUMBER(19,2), 
	"LOCATION" NUMBER(19,2), 
	"MODEL" NUMBER(19,2), 
	"TRANSMISSION" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RENTERS
--------------------------------------------------------

  CREATE TABLE "CAR_RENTAL"."RENTERS" 
   (	"ID" NUMBER(19,2), 
	"EMAIL" VARCHAR2(320 CHAR), 
	"NAME" VARCHAR2(40 CHAR), 
	"PHONE" VARCHAR2(9 CHAR), 
	"SURNAME" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CAR_RENTAL.BOOKING
SET DEFINE OFF;
Insert into CAR_RENTAL.BOOKING (ID,PRICE,SINCE,UNTIL,CAR,RENTER) values ('6','700',to_date('15/12/22','RR/MM/DD'),to_date('15/12/29','RR/MM/DD'),'2','6');
Insert into CAR_RENTAL.BOOKING (ID,PRICE,SINCE,UNTIL,CAR,RENTER) values ('7','100',to_date('15/12/06','RR/MM/DD'),to_date('15/12/07','RR/MM/DD'),'2','7');
REM INSERTING into CAR_RENTAL.CARS
SET DEFINE OFF;
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('1','101','1100','2','1','1','1','1','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('2','150','1210','2','4','1','1','1','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('5','174','1320','1','2','1','1','2','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('7','225','1610','5','1','1','1','3','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('9','170','1650','4','2','3','1','4','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('12','170','1230','2','6','2','1','5','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('14','193','1520','1','1','2','1','6','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('15','193','1520','1','3','2','1','6','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('17','143','1360','2','2','2','1','6','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('20','360','1440','5','1','2','1','6','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('22','200','1790','6','1','2','1','6','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('24','355','2125','4','1','3','1','7','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('26','60','1100','2','5','1','1','8','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('27','60','1100','2','4','1','1','8','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('28','60','1100','2','7','1','1','8','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('29','90','1150','2','1','1','1','8','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('30','90','1150','2','2','1','1','8','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('36','140','1310','6','2','1','1','9','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('37','140','1310','6','2','1','1','9','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('40','54','650','2','5','1','1','10','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('42','103','1400','3','2','1','1','11','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('46','100','1100','2','1','1','1','13','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('47','100','1100','2','2','1','1','13','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('50','197','1350','1','1','1','1','14','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('51','197','1350','1','3','1','1','14','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('55','175','1345','1','3','1','1','16','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('56','175','1345','1','1','1','1','16','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('58','225','1645','4','2','1','1','17','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('59','560','1645','5','1','2','1','18','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('61','184','1720','1','1','2','1','18','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('63','388','1820','5','3','2','1','19','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('65','95','1100','2','5','1','1','20','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('69','190','1456','4','7','3','1','22','1');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('74','115','1210','2','2','1','1','24','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('75','140','1210','1','2','1','1','24','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('76','125','1210','6','2','1','1','24','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('80','177','1445','6','1','2','1','25','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('84','106','1150','3','4','1','1','27','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('86','115','1140','2','2','1','1','28','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('87','115','1140','2','1','1','1','28','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('90','150','1230','1','1','1','1','29','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('92','65','850','2','7','1','1','30','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('94','181','1570','4','1','3','1','31','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('97','105','1150','6','5','1','1','33','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('99','150','1350','2','2','1','1','34','2');
Insert into CAR_RENTAL.CARS (ID,POWER,WEIGHT,BODY,COLOR,WHEELS,LOCATION,MODEL,TRANSMISSION) values ('101','180','1415','6','2','1','1','35','2');
REM INSERTING into CAR_RENTAL.RENTERS
SET DEFINE OFF;
Insert into CAR_RENTAL.RENTERS (ID,EMAIL,NAME,PHONE,SURNAME) values ('6','sa@s','a','987654321','s');
Insert into CAR_RENTAL.RENTERS (ID,EMAIL,NAME,PHONE,SURNAME) values ('7','as@w','qwert','543534451','sadf');
--------------------------------------------------------
--  DDL for Index SYS_C0010006
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAR_RENTAL"."SYS_C0010006" ON "CAR_RENTAL"."RENTERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010569
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAR_RENTAL"."SYS_C0010569" ON "CAR_RENTAL"."BOOKING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010947
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAR_RENTAL"."SYS_C0010947" ON "CAR_RENTAL"."CARS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("SINCE" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("UNTIL" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("CAR" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" MODIFY ("RENTER" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."BOOKING" ADD CONSTRAINT "BOOKING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARS
--------------------------------------------------------

  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("POWER" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("BODY" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("WHEELS" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" MODIFY ("TRANSMISSION" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."CARS" ADD CONSTRAINT "CARS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENTERS
--------------------------------------------------------

  ALTER TABLE "CAR_RENTAL"."RENTERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."RENTERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CAR_RENTAL"."RENTERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "CAR_RENTAL"."BOOKING" ADD CONSTRAINT "BOOKING_CAR_FK" FOREIGN KEY ("CAR")
	  REFERENCES "CAR_RENTAL"."CARS" ("ID") ENABLE;
  ALTER TABLE "CAR_RENTAL"."BOOKING" ADD CONSTRAINT "BOOKING_RENTER_FK" FOREIGN KEY ("RENTER")
	  REFERENCES "CAR_RENTAL"."RENTERS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOOKING_SORT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CAR_RENTAL"."BOOKING_SORT_TRG" 
AFTER INSERT ON BOOKING
FOR EACH ROW
DECLARE
  TYPE renter_row IS RECORD (
    ID renters.id%TYPE,
    EMAIL renters.email%TYPE,
    NAME renters.name%TYPE,
    PHONE renters.phone%TYPE,
    SURNAME renters.surname%TYPE
  );
  renter renter_row;
BEGIN
  DELETE FROM BOOKING_WRO WHERE ID = :NEW.ID;
  SELECT * INTO renter FROM RENTERS_WRO WHERE ID = :NEW.RENTER;
  INSERT INTO RENTERS (ID, EMAIL, NAME, PHONE, SURNAME) VALUES (renter.ID, renter.EMAIL, renter.NAME, renter.PHONE, renter.SURNAME);
  DELETE FROM RENTERS_WRO WHERE ID = :NEW.RENTER;
END;
/
ALTER TRIGGER "CAR_RENTAL"."BOOKING_SORT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CARS_SORT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CAR_RENTAL"."CARS_SORT_TRG" 
AFTER INSERT ON CARS 
FOR EACH ROW
BEGIN
  DELETE FROM CARS_WRO WHERE ID = :NEW.ID;
END;
/
ALTER TRIGGER "CAR_RENTAL"."CARS_SORT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn BOOKING_WRO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "CAR_RENTAL"."BOOKING_WRO" FOR "CAR_RENTAL"."BOOKING"@"PLUG_CARS_DB";
--------------------------------------------------------
--  DDL for Synonymn CARS_WRO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "CAR_RENTAL"."CARS_WRO" FOR "CAR_RENTAL"."CARS"@"PLUG_CARS_DB";
--------------------------------------------------------
--  DDL for Synonymn RENTERS_WRO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE SYNONYM "CAR_RENTAL"."RENTERS_WRO" FOR "CAR_RENTAL"."RENTERS"@"PLUG_CARS_DB";
