create or replace TRIGGER BODIES_TRG BEFORE INSERT ON BODIES FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT BODIES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER BOOKING_TRG BEFORE INSERT ON BOOKING FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT BOOKING_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER CARS_TRG BEFORE INSERT ON CARS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT CARS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER COLORS_TRG BEFORE INSERT ON COLORS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT COLORS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER LOCATIONS_TRG BEFORE INSERT ON LOCATIONS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT LOCATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER MANUFACTURERS_TRG BEFORE INSERT ON MANUFACTURERS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT MANUFACTURERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER MODELS_TRG BEFORE INSERT ON MODELS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT MODELS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER RENTERS_TRG BEFORE INSERT ON RENTERS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT RENTERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER TRANSMISSIONS_TRG BEFORE INSERT ON TRANSMISSIONS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT TRANSMISSIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;
create or replace TRIGGER WHEELS_TRG BEFORE INSERT ON WHEELS FOR EACH ROW BEGIN IF (INSERTING AND :NEW.ID IS NULL) THEN SELECT WHEELS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL; END IF; END; ;

insert into BODIES values (null, 'SEDAN');
insert into BODIES values (null, 'HATCHBACK');
insert into BODIES values (null, 'MPV');
insert into BODIES values (null, 'SUV');
insert into BODIES values (null, 'COUPE');
insert into BODIES values (null, 'TRUCK');

insert into COLORS values (null, 'BLACK');
insert into COLORS values (null, 'WHITE');
insert into COLORS values (null, 'RED');
insert into COLORS values (null, 'GREEN');
insert into COLORS values (null, 'BLUE');
insert into COLORS values (null, 'YELLOW');
insert into COLORS values (null, 'BROWN');
insert into COLORS values (null, 'PURPLE');

insert into WHEELS values (null, 'FRONT');
insert into WHEELS values (null, 'REAR');
insert into WHEELS values (null, '_4x4');

insert into TRANSMISSIONS values (null, 'AUTO');
insert into TRANSMISSIONS values (null, 'MANUAL');
